CREATE TABLE IF NOT EXISTS L0_t1 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t2 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t3 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t4 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t5 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t6 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER,
  c4 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t7 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER,
  c4 INTEGER,
  c5 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t8 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t9 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L0_t10 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER,
  c4 INTEGER
);
CREATE TABLE IF NOT EXISTS L1_t1 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L1_t2 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER,
  c4 INTEGER,
  c5 INTEGER
);
CREATE TABLE IF NOT EXISTS L1_t3 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER,
  c4 INTEGER
);
CREATE TABLE IF NOT EXISTS L2_t1 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L2_t2 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L2_t3 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L3_t1 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L3_t2 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L3_t3 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L3_t4 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
CREATE TABLE IF NOT EXISTS L3_t5 (
  c1 INTEGER,
  c2 INTEGER,
  c3 INTEGER
);
